### PR TITLE
Improving Router HA Documentation

### PR DESCRIPTION
**Pull request by SocalNick**

### CODE REVIEW

**Comment by SocalNick** [comment]
cc @crhino @shalako want to check me on this?

**Comment by shalako** [comment]
How about 

"Scale the router relative to the total load for all applications running on Cloud Foundry. In general, the router is CPU bound and can be scaled vertically by increasing available CPU, after which, it can be scaled horizontally."

**Comment by SocalNick** [comment]
Done

**Comment by bentarnoff** [comment]
Thanks, @SocalNick !

**Pull request merged**
