### PR TITLE
Add permission for sharing private domains

### PR DESCRIPTION
**Pull request by cwlbraa**
Hello from CAPI!

Please do not merge until our PM, @zrob has had a chance to review these changes.

Finishes [#158923727](https://www.pivotaltracker.com/story/show/158923727)

Thanks!

/cc @mkenyon

### CODE REVIEW

**Comment by zrob** [comment]
looks good

**Comment by pspinrad** [comment]
Thanks @cwlbraa and @zrob -- any previous versions of CAPI this should apply to?  Wanna know if we should cherrypick this change to branches 2.2, 1.15, 283 etc.

**Comment by cwlbraa** [comment]
should be 2.3+ only.

```
which_capi 5d6bdda58
First CAPI release: 1.60.0
```

(2.2 is 1.58.x)

**Comment by pspinrad** [comment]
@cwlbraa thanks!

**Pull request merged**
