### PR TITLE
Fix inconsistency between process_cpu.shares formula and text description

### PR DESCRIPTION
**Pull request by FlorentFlament**

### CODE REVIEW

**Comment by pspinrad** [comment]
@zrob -- can you please verify the math that this revision to the formula represents:

> Cloud Foundry scales
the number of allocated shares linearly with the amount of memory, with an app
instance requesting 8G of memory getting the upper limit of 1024 shares.

Thanks!

**Comment by zrob** [comment]
looks right to me.  poking @emalm who is very familiar with this

and don't forget CLAs :)

**Comment by pspinrad** [comment]
@zrob thanks, and yes @FlorentFlament , please sign the CLA, see above.

**Comment by emalm** [comment]
Using "min" instead of "max" is correct, but the formula is in general not well defined because the units of `application_memory` are not specified. Either `process_cpu.shares = min( (application_memory / 8 MB), 1024)` or `process_cpu.shares = min( 1024 * (application_memory / 8 GB), 1024)` would pass [dimensional analysis](https://en.wikipedia.org/wiki/Dimensional_analysis), though.

**Comment by FlorentFlament** [comment]
Indeed, the `application_memory` unit is missing. I updated my pull request with: `process_cpu.shares = min( 1024 * (application_memory / 8 GB), 1024)` for more clarity.
Also, I sent my CLA.

**Comment by christopherclark** [comment]
CLA: A-OK

**Comment by pspinrad** [comment]
Thanks all! @FlorentFlament @zrob @emalm @christopherclark

**Pull request merged**
